version: '3'

services:
  api:
    build: .
    environment:
      - CACHE_MINUTES=15
    labels:
      - traefik.enable=true
      - traefik.http.routers.strapi.rule=Host(`donation-api.roulerpouraider.fr`)
      - traefik.http.routers.strapi.entrypoints=websecure
      - traefik.http.routers.strapi.tls.certresolver=letsencryptresolver
      - traefikk.ports=80
    networks:
      - traefik

networks:
  traefik:
    external: true