version: '3'

services:
  api:
    container_name: "api-scrapt-donations"
    build: .
    environment:
      - CACHE_MINUTES=15
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.donation-api.rule=Host(`donation-api.roulerpouraider.fr`)
      - traefik.http.routers.donation-api.entrypoints=web,websecure
      - traefik.http.routers.donation-api.tls.certresolver=letsencryptresolver
      - traefik.http.services.donation-api.loadbalancer.server.port=80
      - traefik.docker.network=traefik
      - traefik.port=80
    networks:
      - traefik

networks:
  traefik:
    name: "traefik"
    external: true
