version: '3'

services:
  api:
    build: .
    environment:
      - CACHE_MINUTES=15
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.donation_api.rule=Host(`donation-api.roulerpouraider.fr`)
      - traefik.http.routers.donation_api.entrypoints=websecure
      - traefik.http.routers.donation_api.tls.certresolver=letsencryptresolver
      - traefikk.ports=80
    networks:
      - traefik

networks:
  traefik:
    external: true